
import {Outfit, Inter} from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs';
import "./globals.css";
import Provider from "./provider";
import PropTypes from 'prop-types';

const outfit=Outfit({subsets:["latin"]})
const inter = Inter({ 
  subsets: ['latin'],
  display: 'swap' // Add display swap for better performance
})

export const metadata = {
  title: "GenVid",
  description: "Generated by create next app",
}
export default function RootLayout({children}) {
  RootLayout.propTypes = {
    children: PropTypes.node.isRequired
  };
  return (
    <ClerkProvider>
    <html lang="en">
    <head>
        {/* Add proper 'as' attribute to preloaded resources */}
        <link 
          rel="preload"
          href="/fonts/Outfit.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      </head>
      <body  
      className={`${inter.className} ${outfit.className}`}>
        <Provider>
         {children}
        </Provider>
        
      </body>
    </html>
    </ClerkProvider>
  );
}
